handle byzer python script stacktrace
byzer-org/byzer-notebook pull request #130
Opened 2022-04-02 06:24 UTC by MichelZhan

2022-04-13 08:59 UTC, chncaesar requested changes

2022-04-13 08:59 UTC, chncaesar commented on src/main/java/io/kyligence/notebook/console/util/EngineExceptionUtils.java
> +package io.kyligence.notebook.console.util;
Unit test for this class, Please

2022-04-14 07:09 UTC, MichelZhan commented on src/main/java/io/kyligence/notebook/console/util/EngineExceptionUtils.java
> +package io.kyligence.notebook.console.util;
added in JobServiceTest

2022-04-17 08:54 UTC, chncaesar approved these changes

2022-04-17 08:54 UTC, merged