#115 optimize byzer script
byzer-org/byzer-notebook pull request #134
Opened 2022-04-02 13:32 UTC by AdmondGuo

2022-04-02 13:38 UTC, AdmondGuo commented
BIP：https://github.com/byzer-org/byzer-notebook/wiki/BIP-2%5Bdraft%5D:-Optimize-Notebook-scripts
issue：#115

2022-04-06 08:20 UTC, ZhengshuaiPENG requested changes

2022-04-06 08:20 UTC, ZhengshuaiPENG commented on src/main/java/io/kyligence/notebook/console/util/NotebookConfigCLI.java
> +                System.out.println("Example: NotebookConfigCLI kylin.server.mode");
这里 kylin 的例子换成 notebook 的

2022-04-06 08:20 UTC, ZhengshuaiPENG commented on src/main/java/io/kyligence/notebook/console/util/Unsafe.java
> + *
这个 license 是 kyligence 的，去掉

2022-04-06 08:44 UTC, chncaesar requested changes

2022-04-06 08:45 UTC, ZhengshuaiPENG commented on build/bootstrap.sh
> +function runTool() {
runTool 应该是执行写的 mysql redis XXXXCLI 的封装的方法吧

2022-04-19 12:46 UTC, ZhengshuaiPENG approved these changes

2022-04-23 15:44 UTC, merged